---
abstract: 'The great new Data::ParseBinary::Network::Ccsds!'
author:
  - 'Laurent KISLAIRE, C<< <teebeenator at gmail.com> >>'
  - 'Laurent KISLAIRE <teebeenator@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-ParseBinary-Network-Ccsds
no_index:
  directory:
    - inc
    - t
requires:
  Data::ParseBinary: 0.27
  Digest::CRC: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
